### ISSUE TITLE
other ports

### ISSUE THREAD

**Issue by sqift** [RhinoSecurityLabs/IPRotate_Burp_Extension#14]
Hi, thx for extension :-)
Is it possible to set an arbitrary port for requests?
Aws writes that it`s possible (https://docs.aws.amazon.com/en_us/apigateway/latest/developerguide/setup-http-integrations.html)
I started the server on 80 and 8080 port. So I created api for 80 port, checked browser - on the server  i had seen aws ip. So I created api for 8080 port, when i requested my server in browser then i had seen my host address.

**Comment by sqift** [comment]
I was wrong, it does not work in both cases, if you write example.com:80 or example.com:8080

**Comment by DaveYesland** [comment]
Thanks for pointing this out, should be fixed.
