### ISSUE TITLE
how to configure aws api gateway?

### ISSUE THREAD

**Issue by possib1e** [RhinoSecurityLabs/IPRotate_Burp_Extension#16]
I create a new access key ,secret key, but the enable label could not work if i select any regions(select no regions the enable label could work). Could you please teach me how to configure the aws api gateway?

**Comment by DaveYesland** [comment]
I am guessing your AWS user you have configured does not have the proper permissions to use API gateway. Check out this article, it may help https://docs.aws.amazon.com/apigateway/latest/developerguide/permissions.html 
You may also want to look in the Burp extension console for any output which may let you know what is going on.

**Comment by RookieTerry** [comment]
So what type of API Gateway should I choose?HTTP,Websocket or REST API Gateway?
