### ISSUE TITLE
getting 504 Gateway Timeout

### ISSUE THREAD

**Issue by superuser5** [RhinoSecurityLabs/IPRotate_Burp_Extension#17]
using IP Rotate extension and it is enabled with HTTP, i get the following error very often:

HTTP/1.1 504 Gateway Timeout
Date: Fri, 21 Feb 2020 00:13:02 GMT
Content-Type: application/json
Content-Length: 56
Connection: close
x-amzn-RequestId: 7977e648-d183-47c2-a416-6f04c23e8e5d
x-amzn-ErrorType: InternalServerErrorException
x-amz-apigw-id: IOIGVEoIrPEFfJg=

{"message": "Network error communicating with endpoint"}

**Comment by DaveYesland** [comment]
Sorry, without more information I do not know what could  be causing this.
