### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by 0xShin** [RhinoSecurityLabs/IPRotate_Burp_Extension#20]
Hello guys, I was just wondering if you could help me with this problem in burp. I followed your instructions in the `Usage` even used the aws credentials of root so that I can have full access to the api gateway but the problem is that somehow there's a authentication failure when reaching out to the apis that were made through this extension, it looks like the following below.

![image](https://user-images.githubusercontent.com/50789123/81365947-1d9a8880-911c-11ea-91e6-24442657539b.png)

Does anyone  have a clue what's going on?

**Comment by DaveYesland** [comment]
Sorry not sure what this is with just that output. I would assume it is an issues with the permissions on the keys you are using.
