### ISSUE TITLE
add in other regions please

### ISSUE THREAD

**Issue by AnotherWayIn** [RhinoSecurityLabs/IPRotate_Burp_Extension#22]
Some of our clients geo restrict. i know i can modify the code, but it'd be nice to have these in the bapp store

thanks :)

**Comment by DaveYesland** [comment]
Fixed with https://github.com/RhinoSecurityLabs/IPRotate_Burp_Extension/commit/60aba571d7bcebc94a365c0c6d80b5b9e535dc16
