### ISSUE TITLE
bug with specifying port

### ISSUE THREAD

**Issue by AnotherWayIn** [RhinoSecurityLabs/IPRotate_Burp_Extension#23]
Hi,

I think there's a request issue when using against targets on non-standard ports.
thanks

**Comment by DaveYesland** [comment]
Do you have an error message or any information related to the issue your having? How can this be reproduced?

**Comment by AnotherWayIn** [comment]
Sure, so when you need to hit target example.com:8080 I add the port within the Target host field, but the request goes direct rather than through a gateway. The port gets stripped out in the code I think.
thanks

![image](https://user-images.githubusercontent.com/10500665/83204500-94a4c900-a17e-11ea-84ef-4ffde255831d.png)

**Comment by DaveYesland** [comment]
Just tested this and I am still getting API gateway IPs when I set my target to somehost.com:8080. Is there maybe something else going on here? Are you targeting localhost or something when testing this? Are you setting the port in "Target Host" field example.com:8080?

**Comment by AnotherWayIn** [comment]
Yes i'm setting the port. I've tested on other non-standard ports and getting the same:
![image](https://user-images.githubusercontent.com/10500665/83364892-2eff4980-a3d7-11ea-9faf-af83e59f023d.png)

**Comment by DaveYesland** [comment]
Is this installed from the BApp store?
