### ISSUE TITLE
script boto3

### ISSUE THREAD

**Issue by tom88600** [RhinoSecurityLabs/IPRotate_Burp_Extension#31]
hi everyone
could somebody helps me to load boto3 in burp suite in order to change my ip with IP_rotate?
I don't know which script i have to write to establish a connection with the aws cloud??
Thank you

**Comment by DaveYesland** [comment]
You will need boto3 installed: https://pypi.org/project/boto3/.  This video also walks through the setup and may be helpful: https://www.youtube.com/watch?v=_YQLao6p9GM
