### ISSUE TITLE
IP not getting changed

### ISSUE THREAD

**Issue by rasiras** [RhinoSecurityLabs/IPRotate_Burp_Extension#33]
hello team

i just setup my IP rotate addon and enabled it for ifconfig.io to see if my ip is changing in every request by ip is not getting changed. but addon is showing enabled for ifconfig.io 
![iprotate](https://user-images.githubusercontent.com/25229330/103287325-26590b00-49da-11eb-9ba4-2286189c96ba.png)

adding screenshots of output on extention tab
![ipr](https://user-images.githubusercontent.com/25229330/103287389-530d2280-49da-11eb-9567-573bd400fb2b.png)

**Comment by TheKalin** [comment]
Point curl to the burpsuite instance.. 
```
curl -x http://127.0.0.1:8080 ifconfig.io
```
