### ISSUE TITLE
Is Ip-Rotation Bypass Obsolete?

### ISSUE THREAD

**Issue by ericnyamubbp** [RhinoSecurityLabs/IPRotate_Burp_Extension#36]
Hi,

Thanks allot for this wonderful tool.But there's a slight problem.Nowadays ip rotation bypasses are being rejected as valid security issue because some argue that changing ips will slow down the attack.In your test about this means of bypass do you find that to be true?

Regards

**Comment by DaveYesland** [comment]
I would say yes this method will typically slow down an attack as proxying everything through API Gateway will make things slower. But I have been able to prove impact using this method even though it may not be as fast as something like turbo intruder. It is completely dependent on what you are attacking and how they have implemented the protections.

**Comment by ericnyamubbp** [comment]
Hi,

Have you been able to use [turbo intruder](https://github.com/PortSwigger/turbo-intruder) with this bypass method?Did you see a marked increase in the request rate?That would be very interesting.

Regard
