### ISSUE TITLE
The security token included in the request is invalid

### ISSUE THREAD

**Issue by YuraSrohiy** [RhinoSecurityLabs/IPRotate_Burp_Extension#39]
When I'm trying to enable IPRotate, enable button is not working, and this message pops in trace

```
Traceback (most recent call last):
  File "/Users/kendirom/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/IPRotate.py", line 202, in enableGateway
    self.startAPIGateway()
  File "/Users/kendirom/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/IPRotate.py", line 76, in startAPIGateway
    self.create_api_response = self.awsclient.create_rest_api(
  File "/Users/kendirom/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/kendirom/.BurpSuite/bapps/2eb2b1cb1cf34cc79cda36f0f9019874/BappModules/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the CreateRestApi operation: The security token included in the request is invalid.
```
Although I'm passing the right keys:

![image](https://user-images.githubusercontent.com/12134512/133121533-19cf3a78-6651-46f7-b348-3c3b4f34dcb6.png)
![image](https://user-images.githubusercontent.com/12134512/133121601-9b473c13-6285-4dc3-8000-38d3d19bf268.png)

Not sure what I'm doing wrong.
Here are extender options:
![image](https://user-images.githubusercontent.com/12134512/133121753-6977d9e2-60ad-4b9b-a007-4203462b13bc.png)

Tried with python 2.7 but had no success also

**Comment by DaveYesland** [comment]
The Access Key and Secret key should be the AWS access key id and access key secret to a role or user in the AWS account which has full permissions for API Gateway, something like: `AKIAIOSFODNN7EXAMPLE`. 

IP rotate will setup all the API Gateways needed there should be no need to do that manually.

https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys

**Comment by YuraSrohiy** [comment]
Thanks! That helped
