### ISSUE TITLE
AWS China problem using your extension

### ISSUE THREAD

**Issue by sarkan902** [RhinoSecurityLabs/IPRotate_Burp_Extension#43]
Hello i tried to edit IPRotate Extension by changing line 
 self.allEndpoints.append(self.restAPIId + '.execute-api.' + region + '.amazonaws.com')
to .com.cn so i can access Chinese API Gateway.

I have chinese Amazon account and i opened regions cn-north-1 and cn-northwest-1. When i tried to make any request then it's giving me 403 code error on request and body is {"Message":null}

Please help me :(
![image](https://user-images.githubusercontent.com/72881843/167657238-0918dc7d-8cdc-48e6-b89e-dd6119bcc08c.png)

I want to add that i tried to make it from API Gateway Panel and it works, but only on amazon panel
![image](https://user-images.githubusercontent.com/72881843/167658247-d89997b8-b2c3-4d1e-b196-ed4e7e7ab9d8.png)

**Comment by DaveYesland** [comment]
I have no way to test AWS China, feel free to fork and work on this for now China region support will not be added to this project.
