### ISSUE TITLE
IPRotate agains multiple host?

### ISSUE THREAD

**Issue by QueTheWizard** [RhinoSecurityLabs/IPRotate_Burp_Extension#48]
Hi, is there an option to define multiple hosts for the IPRotate? or something like *.example.com? and also for both HTTP and HTTPS? 
Thanks

**Comment by DaveYesland** [comment]
There is no option to do this. I do not think this is possible.

**Comment by QueTheWizard** [comment]
Thanks for updating @DaveYesland. All of the above are impossible to implement? including subdomain wildcard or both HTTP/S?

**Comment by DaveYesland** [comment]
You could implement HTTP/S probably by spinning up separate GW for each HTTP and HTTPS and then routing accordingly, but I have no plans to implement this.

Wildcards do not work because GW needs to know the specific domain to route the request to when it is started AFAIK.
