### ISSUE TITLE
{"message":"Missing Authentication Token"}

### ISSUE THREAD

**Issue by theyellowking1603** [RhinoSecurityLabs/IPRotate_Burp_Extension#5]
After successfully adding the extension to burp, and adding my access/secret keys for a user with appropriate api gateway permissions, when browsing to the target I chose I always get the following message:

"{"message":"Missing Authentication Token"}"

**Comment by Frichetten** [comment]
@theyellowking1603, how did you resolve this?

**Comment by theyellowking1603** [comment]
@Frichetten I realised that it was because I was browsing directly to the target I set, e.g:

www.google.com

But if you browse to www.google.com/whatever?etc=sdfsdfsd it works fine.

**Comment by DaveYesland** [comment]
Yes this is an issue I have noticed. Attempting to access the root of a target domain fails through API Gateway with this error. I am going to look into trying to fix this at some point.

**Comment by Frichetten** [comment]
@theyellowking1603, Thank you! I noticed this last week but forgot about it completely. You have saved me like an hour of fiddling around. 

@DaveYesland, thank you for making the tool! I'm really enjoying using it.

**Comment by ThunderSon** [comment]
After a day of researching the issue, I arrived to the issues section and found this. Thank you for clearing this up. I'll try and see if I can help on this issue 😄

**Comment by ThunderSon** [comment]
After doing some research, the code needs to add an `ANY` Method to the `/`, just like it did for the `/{proxy+}` endpoint. Testing it out right now, and will see if I can create a small code snippet and create a PR

**Comment by ThunderSon** [comment]
Assign this to me when possible 😄

**Comment by DaveYesland** [comment]
Thanks!
