### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by z8er5k** [RhinoSecurityLabs/IPRotate_Burp_Extension#52]
('Unable to import boto3, create API Gateway manually using createapigw.py script, and load them from file.', SyntaxError('no viable alternative at input \'"The \'{service_name}\' resource does not an API version of: {bad_api_version}\\n"\'', ('/home/onebone/boto3/boto3/exceptions.py', 43, 13, '            f"The \'{service_name}\' resource does not an API version of: {bad_api_version}\\n"\n')))
load API GW endpoints from file
![Screenshot from 2023-09-06 00-46-53](https://github.com/RhinoSecurityLabs/IPRotate_Burp_Extension/assets/144201141/d46c8ea8-d530-4e7b-b90c-7460751af20f)
![Screenshot from 2023-09-06 00-47-18](https://github.com/RhinoSecurityLabs/IPRotate_Burp_Extension/assets/144201141/5ea1a9e9-ebc7-4d8b-9112-2059f49e8eaa)

**Comment by DaveYesland** [comment]
I have made some changes to this to now include boto3 with the extension. You can try again after a new pull and see if it all works from the UI for you. You can also install from the BApp store and that version should work.
