### ISSUE TITLE
How to set up AWS API Gateway?

### ISSUE THREAD

**Issue by RookieTerry** [RhinoSecurityLabs/IPRotate_Burp_Extension#53]
Could you please add a short tutorial of setting up a AWS API Gateway in README.md?I don't know where to add a set of AWS key and the permission,what type I should choose,and where to get a API GW file.Besides,what is the stagename?

**Comment by DaveYesland** [comment]
The extension itself and the provided createapigateways.py utility are capable of creating the needed API gateways. You should only need AWS credentials with appropriate permissions (admin permissions should always work). Check out some of the tutorials out there on setting this up here is one: https://www.youtube.com/watch?v=_YQLao6p9GM&t=440s
