### ISSUE TITLE
Issues Rotating Through Multiple Regions

### ISSUE THREAD

**Issue by jas594** [RhinoSecurityLabs/IPRotate_Burp_Extension#54]
I never had this bug in the past, but it seems there's now a problem when using a gateway in more than 1 region. Specifically, only every other request gets routed and hits the receiving server. This also seems to be specific to Burp's Intruder as the bug wasn't present when automating curl requests via Burp.

![IPRotate](https://github.com/RhinoSecurityLabs/IPRotate_Burp_Extension/assets/9909519/4aa07445-125f-40d0-938e-9dd2bd098322)

**Comment by DaveYesland** [comment]
I am not seeing this same issue. 
Did you install this from this repo or through the Bapp store?
I notice problems can occur when you have too many concurrent requests, try lowering those to 1 or 3 see if that makes a difference.

**Comment by jas594** [comment]
I was only using 1 thread, but on a similar note to concurrent requests, I noticed this Intruder setting was enabled by default. Disabling it fixed the issue! Can you confirm that you also have this disabled?

![image](https://github.com/RhinoSecurityLabs/IPRotate_Burp_Extension/assets/9909519/c22e4075-4fb4-4197-adf6-54ce3a962e88)

**Comment by DaveYesland** [comment]
Nice, yeah looks like I do have it disabled as well
