### ISSUE TITLE
Source IP logging?

### ISSUE THREAD

**Issue by m3Ik0r** [RhinoSecurityLabs/IPRotate_Burp_Extension#6]
Is it possible you can integrate a feature that would allow logging of all the source IP addresses used? As far as I can see this isn't possible on Burp via logger++

**Comment by YuraSrohiy** [comment]
This

I have IP Rotate working, and if I'm testing it on https://whatismyipaddress.com/ it changes but when I'm trying to do it with other hosts to bypass the rate limit (where I can't check source) it still rate limit me.

I'm doing requests from an external browser through my own chrome extension. All requests are shown in Proxy HTTP history but they are still rated limited.

How can I check if IP Rotator is working properly?
